In [2]:
%pip install numpy

     ---------------------------------------- 0.0/16.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/16.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/16.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/16.5 MB 1.9 MB/s eta 0:00:09
     ---------------------------------------- 0.0/16.5 MB 1.9 MB/s eta 0:00:09
     --------------------------------------- 0.1/16.5 MB 656.4 kB/s eta 0:00:26
     --------------------------------------- 0.1/16.5 MB 573.4 kB/s eta 0:00:29
     --------------------------------------- 0.1/16.5 MB 435.7 kB/s eta 0:00:38
     --------------------------------------- 0.1/16.5 MB 467.6 kB/s eta 0:00:36
     --------------------------------------- 0.1/16.5 MB 400.9 kB/s eta 0:00:41
     --------------------------------------- 0.1/16.5 MB 400.9 kB/s eta 0:00:41
     --------------------------------------- 0.1/16.5 MB 400.9 kB/s eta 0:00:41
     --------------------------------------- 0.1/16.5 MB 400.9 kB/


[notice] A new release of pip is available: 23.0.1 -> 24.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np


In [4]:
myarr = np.array([[1,2,3,4]])

In [5]:
myarr[0,2]

np.int64(3)

In [6]:
myarr.dtype

dtype('int64')

In [7]:
myarr.shape

(1, 4)

In [8]:
myarr[0,3] = 45

myarr

array([[ 1,  2,  3, 45]])

In [10]:
list_array = np.array([[1,2,3],[4,5,6],[7,8,9]])

list_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
list_array.shape

(3, 3)

In [13]:
list_array.size

9

In [15]:
zeroes = np.zeros((2,5))
zeroes

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
range = np.arange(15)
range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
lspace = np.linspace(1,50,10)
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [19]:
emp = np.empty([4,6])
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        9.45754003e-308, 1.89146896e-307, 7.56571288e-307],
       [3.11525958e-307, 1.24610723e-306, 1.37962320e-306,
        1.29060871e-306, 2.22518251e-306, 1.33511969e-306],
       [1.78022342e-306, 1.05700345e-307, 1.24610383e-306,
        1.69118108e-306, 8.06632139e-308, 1.20160711e-306],
       [1.69119330e-306, 1.29062229e-306, 6.89804133e-307,
        1.11261162e-306, 8.34443015e-308, 8.34402698e-308]])

In [21]:
emp_like = np.empty_like(lspace)
emp_like

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [22]:
ide = np.identity(45)
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [23]:
ide.shape

(45, 45)

In [29]:
arr = np.arange(99)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [31]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [35]:
arrravel = arr.ravel()
arrravel

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [37]:
x = [[1,2,3],[4,5,6],[7,1,0]]

In [39]:
arr = np.array(x)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [40]:
arr.sum(axis=0)

array([12,  8,  9])

In [41]:
arr.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [45]:
for item in arr.flat:
    print (item)

1
2
3
4
5
6
7
1
0


In [46]:
arr.size

9

In [49]:
one = np.array([1,2,7,1,4])
one.argmax()

np.int64(2)

In [50]:
one.argsort()

array([0, 3, 1, 4, 2])

In [51]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 = np.array([[4,2,4],[8,5,6],[12,4,1]])

In [52]:
arr * arr2

array([[ 4,  4, 12],
       [32, 25, 36],
       [84,  4,  0]])

In [53]:
arr + arr2

array([[ 5,  4,  7],
       [12, 10, 12],
       [19,  5,  1]])

In [54]:
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [55]:
arr.max()

np.int64(7)

In [56]:
arr.min()

np.int64(0)

In [57]:
np.where(arr>5)

(array([1, 2]), array([2, 0]))